name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run-script build

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "dist"
          filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.node-version }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.node-version }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}